import pandas as pd

fileName2000_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-01-equities.csv"
data2000_01 = pd.read_csv(fileName2000_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-02-equities.csv"
data2000_02 = pd.read_csv(fileName2000_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-03-equities.csv"
data2000_03 = pd.read_csv(fileName2000_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-04-equities.csv"
data2000_04 = pd.read_csv(fileName2000_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-05-equities.csv"
data2000_05 = pd.read_csv(fileName2000_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-06-equities.csv"
data2000_06 = pd.read_csv(fileName2000_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-07-equities.csv"
data2000_07 = pd.read_csv(fileName2000_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-08-equities.csv"
data2000_08 = pd.read_csv(fileName2000_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-09-equities.csv"
data2000_09 = pd.read_csv(fileName2000_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-10-equities.csv"
data2000_10 = pd.read_csv(fileName2000_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-11-equities.csv"
data2000_11 = pd.read_csv(fileName2000_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
fileName2000_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/all_data/2000-12-equities.csv"
data2000_12 = pd.read_csv(fileName2000_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int},low_memory=False)
frames = [data2000_01,data2000_02,data2000_03,data2000_04,data2000_05,data2000_06,data2000_07,data2000_08,data2000_09,data2000_10,data2000_11,data2000_12]
result = pd.concat(frames)
result.to_csv("C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/full_data_set.csv",sep=",")
'''
fileName2001_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-01-equities.csv"
data2001_01 = pd.read_csv(fileName2001_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-02-equities.csv"
data2001_02 = pd.read_csv(fileName2001_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-03-equities.csv"
data2001_03 = pd.read_csv(fileName2001_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-04-equities.csv"
data2001_04 = pd.read_csv(fileName2001_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-05-equities.csv"
data2001_05 = pd.read_csv(fileName2001_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-06-equities.csv"
data2001_06 = pd.read_csv(fileName2001_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-07-equities.csv"
data2001_07 = pd.read_csv(fileName2001_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-08-equities.csv"
data2001_08 = pd.read_csv(fileName2001_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-09-equities.csv"
data2001_09 = pd.read_csv(fileName2001_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-10-equities.csv"
data2001_10 = pd.read_csv(fileName2001_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-11-equities.csv"
data2001_11 = pd.read_csv(fileName2001_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2001_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2001_4.0-Equities/RPNA_DJEdition_2001_4.0-Equities/2001-12-equities.csv"
data2001_12 = pd.read_csv(fileName2001_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2002_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-01-equities.csv"
data2002_01 = pd.read_csv(fileName2002_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-02-equities.csv"
data2002_02 = pd.read_csv(fileName2002_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-03-equities.csv"
data2002_03 = pd.read_csv(fileName2002_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-04-equities.csv"
data2002_04 = pd.read_csv(fileName2002_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-05-equities.csv"
data2002_05 = pd.read_csv(fileName2002_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-06-equities.csv"
data2002_06 = pd.read_csv(fileName2002_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-07-equities.csv"
data2002_07 = pd.read_csv(fileName2002_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-08-equities.csv"
data2002_08 = pd.read_csv(fileName2002_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-09-equities.csv"
data2002_09 = pd.read_csv(fileName2002_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-10-equities.csv"
data2002_10 = pd.read_csv(fileName2002_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-11-equities.csv"
data2002_11 = pd.read_csv(fileName2002_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2002_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2002_4.0-Equities/RPNA_DJEdition_2002_4.0-Equities/2002-12-equities.csv"
data2002_12 = pd.read_csv(fileName2002_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2003_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-01-equities.csv"
data2003_01 = pd.read_csv(fileName2003_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-02-equities.csv"
data2003_02 = pd.read_csv(fileName2003_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-03-equities.csv"
data2003_03 = pd.read_csv(fileName2003_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-04-equities.csv"
data2003_04 = pd.read_csv(fileName2003_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-05-equities.csv"
data2003_05 = pd.read_csv(fileName2003_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-06-equities.csv"
data2003_06 = pd.read_csv(fileName2003_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-07-equities.csv"
data2003_07 = pd.read_csv(fileName2003_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-08-equities.csv"
data2003_08 = pd.read_csv(fileName2003_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-09-equities.csv"
data2003_09 = pd.read_csv(fileName2003_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-10-equities.csv"
data2003_10 = pd.read_csv(fileName2003_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-11-equities.csv"
data2003_11 = pd.read_csv(fileName2003_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2003_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2003_4.0-Equities/RPNA_DJEdition_2003_4.0-Equities/2003-12-equities.csv"
data2003_12 = pd.read_csv(fileName2003_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2004_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-01-equities.csv"
data2004_01 = pd.read_csv(fileName2004_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-02-equities.csv"
data2004_02 = pd.read_csv(fileName2004_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-03-equities.csv"
data2004_03 = pd.read_csv(fileName2004_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-04-equities.csv"
data2004_04 = pd.read_csv(fileName2004_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-05-equities.csv"
data2004_05 = pd.read_csv(fileName2004_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-06-equities.csv"
data2004_06 = pd.read_csv(fileName2004_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-07-equities.csv"
data2004_07 = pd.read_csv(fileName2004_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-08-equities.csv"
data2004_08 = pd.read_csv(fileName2004_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-09-equities.csv"
data2004_09 = pd.read_csv(fileName2004_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-10-equities.csv"
data2004_10 = pd.read_csv(fileName2004_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-11-equities.csv"
data2004_11 = pd.read_csv(fileName2004_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2004_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2004_4.0-Equities/RPNA_DJEdition_2004_4.0-Equities/2004-12-equities.csv"
data2004_12 = pd.read_csv(fileName2004_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2005_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-01-equities.csv"
data2005_01 = pd.read_csv(fileName2005_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-02-equities.csv"
data2005_02 = pd.read_csv(fileName2005_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-03-equities.csv"
data2005_03 = pd.read_csv(fileName2005_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-04-equities.csv"
data2005_04 = pd.read_csv(fileName2005_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-05-equities.csv"
data2005_05 = pd.read_csv(fileName2005_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-06-equities.csv"
data2005_06 = pd.read_csv(fileName2005_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-07-equities.csv"
data2005_07 = pd.read_csv(fileName2005_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-08-equities.csv"
data2005_08 = pd.read_csv(fileName2005_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-09-equities.csv"
data2005_09 = pd.read_csv(fileName2005_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-10-equities.csv"
data2005_10 = pd.read_csv(fileName2005_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-11-equities.csv"
data2005_11 = pd.read_csv(fileName2005_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2005_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2005_4.0-Equities/RPNA_DJEdition_2005_4.0-Equities/2005-12-equities.csv"
data2005_12 = pd.read_csv(fileName2005_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2006_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-01-equities.csv"
data2006_01 = pd.read_csv(fileName2006_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-02-equities.csv"
data2006_02 = pd.read_csv(fileName2006_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-03-equities.csv"
data2006_03 = pd.read_csv(fileName2006_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-04-equities.csv"
data2006_04 = pd.read_csv(fileName2006_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-05-equities.csv"
data2006_05 = pd.read_csv(fileName2006_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-06-equities.csv"
data2006_06 = pd.read_csv(fileName2006_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-07-equities.csv"
data2006_07 = pd.read_csv(fileName2006_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-08-equities.csv"
data2006_08 = pd.read_csv(fileName2006_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-09-equities.csv"
data2006_09 = pd.read_csv(fileName2006_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-10-equities.csv"
data2006_10 = pd.read_csv(fileName2006_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-11-equities.csv"
data2006_11 = pd.read_csv(fileName2006_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2006_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2006_4.0-Equities/RPNA_DJEdition_2006_4.0-Equities/2006-12-equities.csv"
data2006_12 = pd.read_csv(fileName2006_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2007_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-01-equities.csv"
data2007_01 = pd.read_csv(fileName2007_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-02-equities.csv"
data2007_02 = pd.read_csv(fileName2007_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-03-equities.csv"
data2007_03 = pd.read_csv(fileName2007_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-04-equities.csv"
data2007_04 = pd.read_csv(fileName2007_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-05-equities.csv"
data2007_05 = pd.read_csv(fileName2007_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-06-equities.csv"
data2007_06 = pd.read_csv(fileName2007_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-07-equities.csv"
data2007_07 = pd.read_csv(fileName2007_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-08-equities.csv"
data2007_08 = pd.read_csv(fileName2007_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-09-equities.csv"
data2007_09 = pd.read_csv(fileName2007_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-10-equities.csv"
data2007_10 = pd.read_csv(fileName2007_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-11-equities.csv"
data2007_11 = pd.read_csv(fileName2007_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2007_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2007_4.0-Equities/RPNA_DJEdition_2007_4.0-Equities/2007-12-equities.csv"
data2007_12 = pd.read_csv(fileName2007_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2008_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-01-equities.csv"
data2008_01 = pd.read_csv(fileName2008_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-02-equities.csv"
data2008_02 = pd.read_csv(fileName2008_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-03-equities.csv"
data2008_03 = pd.read_csv(fileName2008_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-04-equities.csv"
data2008_04 = pd.read_csv(fileName2008_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-05-equities.csv"
data2008_05 = pd.read_csv(fileName2008_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-06-equities.csv"
data2008_06 = pd.read_csv(fileName2008_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-07-equities.csv"
data2008_07 = pd.read_csv(fileName2008_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-08-equities.csv"
data2008_08 = pd.read_csv(fileName2008_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-09-equities.csv"
data2008_09 = pd.read_csv(fileName2008_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-10-equities.csv"
data2008_10 = pd.read_csv(fileName2008_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-11-equities.csv"
data2008_11 = pd.read_csv(fileName2008_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2008_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2008_4.0-Equities/RPNA_DJEdition_2008_4.0-Equities/2008-12-equities.csv"
data2008_12 = pd.read_csv(fileName2008_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2009_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-01-equities.csv"
data2009_01 = pd.read_csv(fileName2009_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-02-equities.csv"
data2009_02 = pd.read_csv(fileName2009_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-03-equities.csv"
data2009_03 = pd.read_csv(fileName2009_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-04-equities.csv"
data2009_04 = pd.read_csv(fileName2009_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-05-equities.csv"
data2009_05 = pd.read_csv(fileName2009_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-06-equities.csv"
data2009_06 = pd.read_csv(fileName2009_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-07-equities.csv"
data2009_07 = pd.read_csv(fileName2009_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-08-equities.csv"
data2009_08 = pd.read_csv(fileName2009_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-09-equities.csv"
data2009_09 = pd.read_csv(fileName2009_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-10-equities.csv"
data2009_10 = pd.read_csv(fileName2009_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-11-equities.csv"
data2009_11 = pd.read_csv(fileName2009_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2009_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2009_4.0-Equities/RPNA_DJEdition_2009_4.0-Equities/2009-12-equities.csv"
data2009_12 = pd.read_csv(fileName2009_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2010_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-01-equities.csv"
data2010_01 = pd.read_csv(fileName2010_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-02-equities.csv"
data2010_02 = pd.read_csv(fileName2010_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-03-equities.csv"
data2010_03 = pd.read_csv(fileName2010_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-04-equities.csv"
data2010_04 = pd.read_csv(fileName2010_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-05-equities.csv"
data2010_05 = pd.read_csv(fileName2010_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-06-equities.csv"
data2010_06 = pd.read_csv(fileName2010_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-07-equities.csv"
data2010_07 = pd.read_csv(fileName2010_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-08-equities.csv"
data2010_08 = pd.read_csv(fileName2010_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-09-equities.csv"
data2010_09 = pd.read_csv(fileName2010_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-10-equities.csv"
data2010_10 = pd.read_csv(fileName2010_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-11-equities.csv"
data2010_11 = pd.read_csv(fileName2010_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2010_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2010_4.0-Equities/RPNA_DJEdition_2010_4.0-Equities/2010-12-equities.csv"
data2010_12 = pd.read_csv(fileName2010_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2011_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-01-equities.csv"
data2011_01 = pd.read_csv(fileName2011_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-02-equities.csv"
data2011_02 = pd.read_csv(fileName2011_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-03-equities.csv"
data2011_03 = pd.read_csv(fileName2011_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-04-equities.csv"
data2011_04 = pd.read_csv(fileName2011_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-05-equities.csv"
data2011_05 = pd.read_csv(fileName2011_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-06-equities.csv"
data2011_06 = pd.read_csv(fileName2011_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-07-equities.csv"
data2011_07 = pd.read_csv(fileName2011_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-08-equities.csv"
data2011_08 = pd.read_csv(fileName2011_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-09-equities.csv"
data2011_09 = pd.read_csv(fileName2011_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-10-equities.csv"
data2011_10 = pd.read_csv(fileName2011_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-11-equities.csv"
data2011_11 = pd.read_csv(fileName2011_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2011_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2011_4.0-Equities/RPNA_DJEdition_2011_4.0-Equities/2011-12-equities.csv"
data2011_12 = pd.read_csv(fileName2011_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2012_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-01-equities.csv"
data2012_01 = pd.read_csv(fileName2012_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-02-equities.csv"
data2012_02 = pd.read_csv(fileName2012_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-03-equities.csv"
data2012_03 = pd.read_csv(fileName2012_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-04-equities.csv"
data2012_04 = pd.read_csv(fileName2012_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-05-equities.csv"
data2012_05 = pd.read_csv(fileName2012_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-06-equities.csv"
data2012_06 = pd.read_csv(fileName2012_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-07-equities.csv"
data2012_07 = pd.read_csv(fileName2012_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-08-equities.csv"
data2012_08 = pd.read_csv(fileName2012_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-09-equities.csv"
data2012_09 = pd.read_csv(fileName2012_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-10-equities.csv"
data2012_10 = pd.read_csv(fileName2012_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-11-equities.csv"
data2012_11 = pd.read_csv(fileName2012_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2012_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2012_4.0-Equities/RPNA_DJEdition_2012_4.0-Equities/2012-12-equities.csv"
data2012_12 = pd.read_csv(fileName2012_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2013_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-01-equities.csv"
data2013_01 = pd.read_csv(fileName2013_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-02-equities.csv"
data2013_02 = pd.read_csv(fileName2013_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-03-equities.csv"
data2013_03 = pd.read_csv(fileName2013_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-04-equities.csv"
data2013_04 = pd.read_csv(fileName2013_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-05-equities.csv"
data2013_05 = pd.read_csv(fileName2013_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-06-equities.csv"
data2013_06 = pd.read_csv(fileName2013_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-07-equities.csv"
data2013_07 = pd.read_csv(fileName2013_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-08-equities.csv"
data2013_08 = pd.read_csv(fileName2013_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-09-equities.csv"
data2013_09 = pd.read_csv(fileName2013_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-10-equities.csv"
data2013_10 = pd.read_csv(fileName2013_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-11-equities.csv"
data2013_11 = pd.read_csv(fileName2013_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2013_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2013_4.0-Equities/RPNA_DJEdition_2013_4.0-Equities/2013-12-equities.csv"
data2013_12 = pd.read_csv(fileName2013_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2014_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-01-equities.csv"
data2014_01 = pd.read_csv(fileName2014_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-02-equities.csv"
data2014_02 = pd.read_csv(fileName2014_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-03-equities.csv"
data2014_03 = pd.read_csv(fileName2014_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-04-equities.csv"
data2014_04 = pd.read_csv(fileName2014_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-05-equities.csv"
data2014_05 = pd.read_csv(fileName2014_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-06-equities.csv"
data2014_06 = pd.read_csv(fileName2014_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-07-equities.csv"
data2014_07 = pd.read_csv(fileName2014_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-08-equities.csv"
data2014_08 = pd.read_csv(fileName2014_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-09-equities.csv"
data2014_09 = pd.read_csv(fileName2014_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-10-equities.csv"
data2014_10 = pd.read_csv(fileName2014_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-11-equities.csv"
data2014_11 = pd.read_csv(fileName2014_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2014_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2014_4.0-Equities/RPNA_DJEdition_2014_4.0-Equities/2014-12-equities.csv"
data2014_12 = pd.read_csv(fileName2014_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2015_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-01-equities.csv"
data2015_01 = pd.read_csv(fileName2015_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-02-equities.csv"
data2015_02 = pd.read_csv(fileName2015_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-03-equities.csv"
data2015_03 = pd.read_csv(fileName2015_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-04-equities.csv"
data2015_04 = pd.read_csv(fileName2015_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-05-equities.csv"
data2015_05 = pd.read_csv(fileName2015_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-06-equities.csv"
data2015_06 = pd.read_csv(fileName2015_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-07-equities.csv"
data2015_07 = pd.read_csv(fileName2015_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-08-equities.csv"
data2015_08 = pd.read_csv(fileName2015_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-09-equities.csv"
data2015_09 = pd.read_csv(fileName2015_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-10-equities.csv"
data2015_10 = pd.read_csv(fileName2015_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-11-equities.csv"
data2015_11 = pd.read_csv(fileName2015_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2015_12 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2015_4.0-Equities/RPNA_DJEdition_2015_4.0-Equities/2015-12-equities.csv"
data2015_12 = pd.read_csv(fileName2015_12,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

fileName2016_01 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-01-equities.csv"
data2016_01 = pd.read_csv(fileName2016_01,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_02 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-02-equities.csv"
data2016_02 = pd.read_csv(fileName2016_02,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_03 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-03-equities.csv"
data2016_03 = pd.read_csv(fileName2016_03,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_04 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-04-equities.csv"
data2016_04 = pd.read_csv(fileName2016_04,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_05 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-05-equities.csv"
data2016_05 = pd.read_csv(fileName2016_05,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_06 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-06-equities.csv"
data2016_06 = pd.read_csv(fileName2016_06,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_07 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-07-equities.csv"
data2016_07 = pd.read_csv(fileName2016_07,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_08 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-08-equities.csv"
data2016_08 = pd.read_csv(fileName2016_08,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_09 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-09-equities.csv"
data2016_09 = pd.read_csv(fileName2016_09,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_10 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-10-equities.csv"
data2016_10 = pd.read_csv(fileName2016_10,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})
fileName2016_11 = "C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/decompressed-dataset/RPNA_DJEdition_2016_4.0-Equities/RPNA_DJEdition_2016_4.0-Equities/2016-11-equities.csv"
data2016_11 = pd.read_csv(fileName2016_11,encoding='latin1',dtype={"RELEVANCE":int,"AES":int,"AEV":int,"RP_STORY_EVENT_INDEX":int,"RP_STORY_EVENT_COUNT":int,"CSS":int,"NIP":int,"PEQ":int,"BEE":int,"BMQ":int,"BAM":int,"BCA":int,"BER":int,"ANL_CHG":int,"MCQ":int})

frames = [data2000_01,data2000_02]
#,data2000_03,data2000_04,data2000_05,data2000_06,data2000_07,data2000_08,data2000_09,data2000_10,data2000_11,data2000_12,data2001_01,data2001_02,data2001_03,data2001_04,data2001_05,data2001_06,data2001_07,data2001_08,data2001_09,data2001_10,data2001_11,data2001_12,data2002_01,data2002_02,data2002_03,data2002_04,data2002_05,data2002_06,data2002_07,data2002_08,data2002_09,data2002_10,data2002_11,data2002_12,data2003_01,data2003_02,data2003_03,data2003_04,data2003_05,data2003_06,data2003_07,data2003_08,data2003_09,data2003_10,data2003_11,data2003_12,data2004_01,data2004_02,data2004_03,data2004_04,data2004_05,data2004_06,data2004_07,data2004_08,data2004_09,data2004_10,data2004_11,data2004_12,data2005_01,data2005_02,data2005_03,data2005_04,data2005_05,data2005_06,data2005_07,data2005_08,data2005_09,data2005_10,data2005_11,data2005_12,data2006_01,data2006_02,data2006_03,data2006_04,data2006_05,data2006_06,data2006_07,data2006_08,data2006_09,data2006_10,data2006_11,data2006_12,data2007_01,data2007_02,data2007_03,data2007_04,data2007_05,data2007_06,data2007_07,data2007_08,data2007_09,data2007_10,data2007_11,data2007_12,data2008_01,data2008_02,data2008_03,data2008_04,data2008_05,data2008_06,data2008_07,data2008_08,data2008_09,data2008_10,data2008_11,data2008_12,data2009_01,data2009_02,data2009_03,data2009_04,data2009_05,data2009_06,data2009_07,data2009_08,data2009_09,data2009_10,data2009_11,data2009_12,data2010_01,data2010_02,data2010_03,data2010_04,data2010_05,data2010_06,data2010_07,data2010_08,data2010_09,data2010_10,data2010_11,data2010_12,data2011_01,data2011_02,data2011_03,data2011_04,data2011_05,data2011_06,data2011_07,data2011_08,data2011_09,data2011_10,data2011_11,data2011_12,data2012_01,data2012_02,data2012_03,data2012_04,data2012_05,data2012_06,data2012_07,data2012_08,data2012_09,data2012_10,data2012_11,data2012_12,data2013_01,data2013_02,data2013_03,data2013_04,data2013_05,data2013_06,data2013_07,data2013_08,data2013_09,data2013_10,data2013_11,data2013_12,data2014_01,data2014_02,data2014_03,data2014_04,data2014_05,data2014_06,data2014_07,data2014_08,data2014_09,data2014_10,data2014_11,data2014_12,data2015_01,data2015_02,data2015_03,data2015_04,data2015_05,data2015_06,data2015_07,data2015_08,data2015_09,data2015_10,data2015_11,data2015_12,data2016_01,data2016_02,data2016_03,data2016_04,data2016_05,data2016_06,data2016_07,data2016_08,data2016_09,data2016_10,data2016_11
result = pd.concat(frames)

result.to_csv("C:/Users/emmaj/OneDrive/School/Lake Forest/Freshman Year/Richter Project/full_data_set.csv",sep=",")
'''